### ISSUE TITLE
getting Exact extentx report url

### ISSUE THREAD

**Issue by deepmob** [email2vimalraj/CucumberExtentReporter#100]
Hi there,

I am using ur plugin to send cucumber parallel test reports to ExtentX Server. Is there any way to get the exact extentx url after the test completes? e.g.
http://extentx.abcd.com:1337/#/report-summary?id=5b5501a4a22d7737c4e2447a

**Comment by email2vimalraj** [comment]
Not possible, unless the Extent report gives you that capability. Kindly report this issue in the extent-java repo. Thanks.
