### ISSUE TITLE
Remove "com.cucumber" from the package name

### ISSUE THREAD

**Issue by aslakhellesoy** [email2vimalraj/CucumberExtentReporter#101]
Hi there, I am the creator of Cucumber.

Could you please move all your code to a package that doesn't start with `com.cucumber` or `io.cucumber`.

Your use of the `*.cucumber` domain name confuses users, leading them to believe that your plugin is supported by us.

Thanks,
Aslak

**Comment by email2vimalraj** [comment]
@aslakhellesoy : Apologies for the confusion happened. Sure will do that. Thanks for bringing this up.

**Comment by email2vimalraj** [comment]
Moved all the packages from `com.cucumber` to `com.vimalselvam`.
