### ISSUE TITLE
The way Data Table values are displayed in the report

### ISSUE THREAD

**Issue by dmtraining** [email2vimalraj/CucumberExtentReporter#11]
Hello,

If we use data table in the feature file, is it possible to have 1 line per value (of the data table) in the report file?

For example, in my feature file:
`Given the following animals:`
`| cow   |`
`| horse |`
`| sheep |`

What I would like to see in the report file:
![2016-06-07_1531](https://cloud.githubusercontent.com/assets/15370050/15859491/a7111eb8-2cc5-11e6-9b36-32e59d05fe69.png)

Is it possible?

Thanks.

**Comment by email2vimalraj** [comment]
@dmtraining : It is a new feature to be added in the library. I'll look into this, however I cannot promise you that it will be available in the next release.

**Comment by email2vimalraj** [comment]
This feature is now available in the v2.0.0. Kindly try and re-open in case you find any issues.
