### ISSUE TITLE
The total steps value is wrong

### ISSUE THREAD

**Issue by dmtraining** [email2vimalraj/CucumberExtentReporter#12]
I'm running 1 test but the report displays:
`Total Tests: 2`

![2016-06-09_1035](https://cloud.githubusercontent.com/assets/15370050/15923579/41099a7c-2e2e-11e6-8e4a-112a76e2fb89.png)

**Comment by email2vimalraj** [comment]
You might have to filter to show only Child tests.

**Comment by email2vimalraj** [comment]
Since not heard back from the requestor, closing it.
Kindly re-open in case you face the issue.
