### ISSUE TITLE
Bug and Log tab is not present

### ISSUE THREAD

**Issue by SHasan666** [email2vimalraj/CucumberExtentReporter#14]
Hi, I'm new to Extent report and Cucumber. I was trying to use cucumber with extent report and so far everythings working as expected. But I have noticed one simple thing. Arent we supposed to see the Bug and Log tab in the dashboard? 

![image](https://cloud.githubusercontent.com/assets/20144750/16358751/a2c2632e-3aeb-11e6-8c3a-422b98cf26a1.png)

Here I'm not having those to tabs:

![image](https://cloud.githubusercontent.com/assets/20144750/16358753/b5faa7ee-3aeb-11e6-99b3-014811974d43.png)

Please let me know what I'm doing wrong. Thank you so very much

**Comment by email2vimalraj** [comment]
Fixed and new enhancement added in v1.1.1
