### ISSUE TITLE
Can we use this plugin in JS framework(Protractor)?

### ISSUE THREAD

**Issue by Arunagnz** [email2vimalraj/CucumberExtentReporter#18]
I am using cucumber framework in Protractor. So, Is their any possibility. we can use this in mine?

**Comment by email2vimalraj** [comment]
@Arunagnz : I've never worked on Protractor and it seems the JS testing tool which will add more complications in case you are going to use this library.

I'm closing this since it is out of scope of this library. Kindly re-open in case you have any issues with this library.
