### ISSUE TITLE
GIVEN WHEN THEN AND gherkin keywords are not coming with the steps

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#21]
As Cucumber Gherkin's keywords (GIVEN, WHEN, THEN, AND) are the most important part of this framework. Therefore, it is important to manage these words at front of Step Names
![cucumberextentreports](https://cloud.githubusercontent.com/assets/17103120/17805872/b7fa02b6-6655-11e6-9383-dd65046e3e5f.png)

**Comment by email2vimalraj** [comment]
Feature added in v1.1.1
