### ISSUE TITLE
Convert existing JSON file to extent report html???

### ISSUE THREAD

**Issue by pr4bh4sh** [email2vimalraj/CucumberExtentReporter#24]
Hi, 
I understand that this is not in the scope of this project. It's just a suggestion to show and get introduced to ExtentReporter with least effort for the folks already using cucumber. And later on integrate it with their f/w.
For instance there is a project which has similar objective (https://github.com/leinonen/cucumber-html-report)

Does creating such tool worth the effort ?

**Comment by email2vimalraj** [comment]
Good idea. However as you suggested, this is not a scope of this project. I'll try to give a wider look on this and suggest more on this.

**Comment by email2vimalraj** [comment]
@pr4bh4sh : We are not going to support for json to ExtentReporter converter.
