### ISSUE TITLE
Image is not displaying in the report when giving relative path of the image

### ISSUE THREAD

**Issue by amit89** [email2vimalraj/CucumberExtentReporter#25]
Hi

i am trying to insert image in my extent reports but when i am giving the relative path image is not displaying in the report. below code

		<reportName>
            <![CDATA[
                <img src='/resources/MCK.jpg'/>
            ]]>
		</reportName>

But if i will provide absoulte path in that case it is working fine. 

It would be very helpful if you can tell me how to provide relative path or any other way to provide the image path.

**Comment by email2vimalraj** [comment]
@amit89 : This is an extent report feature. Kindly log an issue over there.
