### ISSUE TITLE
Screenshot support for tests with scenario outlines

### ISSUE THREAD

**Issue by gjarosz** [email2vimalraj/CucumberExtentReporter#27]
## I find scenario outline syntax quite useful for some of my tests, but screenshots are **NOT** embedded into extent reports for tests that use **"Scenario Outline:"** syntax.  
(Please note, that for single scenario everything works fine for me. I have no problems with that)

Please find the problematic code part bellow:
```java  
public void embedding(String s, byte[] bytes) {
if (!scenarioOutlineTest) {
            String extension = (String)MIME_TYPES_EXTENSIONS.get(s);
            String fileName = "screenshot-" + System.currentTimeMillis() + "." + extension;
            this.writeBytesAndClose(bytes, this.reportFileOutputStream(fileName));
            scenarioTest.log(LogStatus.INFO, scenarioTest.addScreenCapture(fileName));
        }
    }
```

## Are there any problems with such support ?

**Comment by email2vimalraj** [comment]
Kindly try the latest version. Reopen in case you have issues.
