### ISSUE TITLE
CucumberExtentReport- Displaying the wrong count of the total test

### ISSUE THREAD

**Issue by perwez123** [email2vimalraj/CucumberExtentReporter#3]
I have created the one feature file and  it has 3 scenario . But in the extent report , It displaying the total test is 4 .I think it includes the count of feature file as well along with the count of the scenario . 

Expected result - It should display the count of scenario only 

I have attached the screen shot for evidence .

![test](https://cloud.githubusercontent.com/assets/10355092/14587701/1a9278dc-04d5-11e6-99a8-d855e4fdfc1f.png)

**Comment by perwez123** [comment]
I have attached another screen shot here , It shows the mismatch of the total count of the scenarios in total test section

Displaying Total Test - 6    , But my actual scenario is 3 only and each scenario consist two step defs . There is another section for total steps where it shows total no of scenario and info (this one is right) . 

Then my question is , Why Total test section display the count ( 6 ) 

Expected result - Total test --> this section should display the total number of scenario only .Should not include the count of steps .

![totaltest](https://cloud.githubusercontent.com/assets/10355092/14587855/2fa61c4e-04d8-11e6-8544-a351c885c5cf.png)

**Comment by anshooarora** [comment]
Van you try with version 2.40.2?  This was one of the bug fixes.

**Comment by perwez123** [comment]
It looks like test view chart showing the correct count now after upgrading to 2.41 . 

Still i am seeing the difference between total test and test view count.

Can you please explain me the difference between Total test and Test view .
As per my understanding , both of these should display the same number ?

If you say Total test display the total steps that exist in the test script then what is Total steps supposed to display?

![t1](https://cloud.githubusercontent.com/assets/10355092/14588418/ff8f1132-04e6-11e6-81f8-919f142139fc.png)

**Comment by anshooarora** [comment]
Can you attach the report here? Let me check once.

**Comment by perwez123** [comment]
Please find the attached zip file .

On Sun, Apr 17, 2016 at 10:03 PM, Anshoo Arora <notifications@github.com>
wrote:

> Can you attach the report here? Let me check once.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211052931>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
I don't see anything in the attachment.

**Comment by perwez123** [comment]
Extract the zip file and open the cucmber.html file .

Didnt you find the cucmber.html in 7zip file

On Sun, Apr 17, 2016 at 10:31 PM, Anshoo Arora <notifications@github.com>
wrote:

> I don't see anything in the attachment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211058661>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
I don't see any attachments in your reply.

**Comment by perwez123** [comment]
I attached the html file here . Please find it below

On Sun, Apr 17, 2016 at 10:36 PM, Perwez Alam <perwez123@gmail.com> wrote:

> Extract the zip file and open the cucmber.html file .
>
> Didnt you find the cucmber.html in 7zip file
>
> On Sun, Apr 17, 2016 at 10:31 PM, Anshoo Arora <notifications@github.com>
> wrote:
>
>> I don't see anything in the attachment.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211058661>
>>
>
>
>
> --
>  Thanks & Regards
>
> *  Md Perwez  Alam*
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
I guess the owner of the repo and the poster can see attachments only..  I am still unable to see them.

**Comment by perwez123** [comment]
Oh then can you ask the owner to check this ? Or can you give your email id
to me so that i can share with you directly?

On Sun, Apr 17, 2016 at 10:51 PM, Anshoo Arora <notifications@github.com>
wrote:

> I guess the owner of the repo and the poster can see attachments only.. I
> am still unable to see them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211063044>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
You can email at anshooarora@gmail.com

**Comment by anshooarora** [comment]
Add this in your extent-config.xml -> scripts and rerun:

```
$('#childNodes').click();
$('#test-count-setting .modal-action').click();
```

Is the issue resolved?

**Comment by perwez123** [comment]
I am not using  extent-config.xml  . Why do i need this xml file ?

On Sun, Apr 17, 2016 at 11:09 PM, Anshoo Arora <notifications@github.com>
wrote:

> Add this in your extent-config.xml -> scripts and rerun:
>
> $('#childNodes').click();
> $('#test-count-setting .modal-action').click();
>
> Is the issue resolved?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211067027>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
To configure only using child tests in the counts, this is part of the test count setting.  Will do the same thing if you click here:

![childnodesonly](https://cloud.githubusercontent.com/assets/4107384/14588889/826cc04c-049a-11e6-9c86-04ed681bd9f5.png)

http://extentreports.relevantcodes.com/java/#configuration

Btw, this seems like a bug, will fix it in the next beta.

**Comment by perwez123** [comment]
Yes I got it .

Parent Test without child test +child tests --> Displaying the wrong count ?
Child Test only -> I think its correct


*Parent test only* - Will this setting display only the feature file count
in case of BDD? As it is showing only 1 test ?




On Sun, Apr 17, 2016 at 11:17 PM, Anshoo Arora <notifications@github.com>
wrote:

> To configure only using child tests in the counts, this is part of the
> test count setting. Will do the same thing if you click here:
>
> [image: childnodesonly]
> <https://cloud.githubusercontent.com/assets/4107384/14588889/826cc04c-049a-11e6-9c86-04ed681bd9f5.png>
>
> http://extentreports.relevantcodes.com/java/#configuration
>
> Btw, this seems like a bug, will fix it in the next beta.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211069081>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by perwez123** [comment]
As I am using this jar for BDD test only , How could i use this
extent-config.xml
. Where to load this config file using extent cucumber ?
Can you please help me to make it work for BDD ?

On Sun, Apr 17, 2016 at 11:29 PM, Perwez Alam <perwez123@gmail.com> wrote:

>
> Yes I got it .
>
> Parent Test without child test +child tests --> Displaying the wrong count
> ?
> Child Test only -> I think its correct
>
>
> *Parent test only* - Will this setting display only the feature file
> count in case of BDD? As it is showing only 1 test ?
>
>
>
>
> On Sun, Apr 17, 2016 at 11:17 PM, Anshoo Arora <notifications@github.com>
> wrote:
>
>> To configure only using child tests in the counts, this is part of the
>> test count setting. Will do the same thing if you click here:
>>
>> [image: childnodesonly]
>> <https://cloud.githubusercontent.com/assets/4107384/14588889/826cc04c-049a-11e6-9c86-04ed681bd9f5.png>
>>
>> http://extentreports.relevantcodes.com/java/#configuration
>>
>> Btw, this seems like a bug, will fix it in the next beta.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211069081>
>>
>
>
>
> --
>  Thanks & Regards
>
> *  Md Perwez  Alam*
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by email2vimalraj** [comment]
Even I'm unable to see any attachments.

**Comment by perwez123** [comment]
I had shared the attachment with Anshoo , He found the issue and will fix
in the next beta



On Mon, Apr 18, 2016 at 10:29 AM, VimalRaj Selvam <notifications@github.com>
wrote:

> Even I'm unable to see any attachments.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/email2vimalraj/CucumberExtentReporter/issues/3#issuecomment-211200435>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by email2vimalraj** [comment]
I'll defer this until I hear from @anshooarora or @perwez123. Let me know once fixed in the next release of extent reporter.

**Comment by email2vimalraj** [comment]
Closing this as this is more of extent reporter has to look into it. Feel free to re-open in case need any help from my side.

**Comment by shwetabodkhe** [comment]
@anshooarora 
Hi, I am using latest com.vimalselvam 3.1.1 for reporting. 
We are generating 2 reports:
1.Summary report using com.vimalselvam
2. Individual report for each test case using AventStack

Individual report is working fine.
In Summary report tests count is same as steps count and even if the test case failed the summary report showing all test passed.
Summary Report:
![summaryreport](https://user-images.githubusercontent.com/42741583/44662446-1bf36480-aa0e-11e8-844a-116db5aabec8.png)

Individual Report
![testcasereport](https://user-images.githubusercontent.com/42741583/44662464-24e43600-aa0e-11e8-9361-e800d4125dca.png)
