### ISSUE TITLE
Screenshot is not working (Unable to integrate screenshot)

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#35]
I have captured the screenshot and get that saved in output folder. Then I wrote below line of code to integrate that screenshot with Extent Cucumber report. It seems integrated successfully but not able to see (open) screenshot.
Reporter.addScreenCaptureFromPath("absolute screenshot path");
![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24434465/4025ad4a-148c-11e7-8698-f5bfe253ca8f.PNG)

**Comment by email2vimalraj** [comment]
@JaspalAujla : What is the path of the screenshot that you have generated?

**Comment by JaspalAujla** [comment]
Actually, I worked with Maven project, it was not working when I directly gave the path, like below (but usually, this way works with Maven project):
Reporter.addScreenCaptureFromPath("output\\screenshot01.png");

However, now it is working when I get the path with system property, like below	Reporter.addScreenCaptureFromPath(System.getProperty("user.dir")+"\\output\\screenshot01.png);

You can close this issue.

**Comment by email2vimalraj** [comment]
@JaspalAujla : Thanks
