### ISSUE TITLE
Examples layout is not aligned

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#36]
Examples table in Cucumber Extent report is not aligned (looks bit awkward), is it possible to align it like Cucumber native HTML report. (Just a suggestion)

![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24475571/c4c1bac6-152c-11e7-887f-d613674c9f32.PNG)

**Comment by email2vimalraj** [comment]
@JaspalAujla : This is how the Extent Report creates the table. I will anyway look into possibilities on how do I make it more elegant.

**Comment by email2vimalraj** [comment]
@JaspalAujla : I've added an enhancement to create a table in the readable format.

Kindly help me to test the feature by following this steps:

1. Clone this repo - `git clone https://github.com/email2vimalraj/CucumberExtentReporter.git`
2. Checkout a feature branch - `git checkout feature-markup-helper`
3. Do maven install - `mvn clean install`
4. Run your tests and see.

Let me know whether you will able to perform tests as I mentioned above.

**Comment by JaspalAujla** [comment]
I have tested it, but it still not looks good. Actually, the table is not designed in a way that it could align the table as per the data in it.
![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24525666/a73bb9cc-15f7-11e7-9e8e-20bec33c26b1.PNG)

 Table in Cucumber native HTML report is handling it in a perfect way:
![cucumberextent2](https://cloud.githubusercontent.com/assets/17103120/24525788/2fff6312-15f8-11e7-82e4-4eaf0f710d01.PNG)

**Comment by email2vimalraj** [comment]
@JaspalAujla : There is a bug in the css produced by extent. I'm sending a PR which should fix that. So till that get merged and released, we'll have to wait.

BTW, the bug is that the width of first column in any table on the test view is set as 60px and the 2nd column is set as 150px.

**Comment by email2vimalraj** [comment]
Update to the latest version 3.0.0 with the latest version of extent report.
