### ISSUE TITLE
No matter where my test scenario (case) failed, the screenshot is always reflecting under Then (last) section

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#37]
My test scenario failed at When section but the screenshot is reflecting under Then section:

![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24477019/fd811ece-1531-11e7-8c5f-aaa2fdf5d8a6.PNG)

![cucumberextent2](https://cloud.githubusercontent.com/assets/17103120/24477023/014c96a0-1532-11e7-9da6-f7de279e7941.PNG)

**Comment by email2vimalraj** [comment]
@JaspalAujla : This should not happen with the latest version of CucumberExtentReport. Kindly share the code to reproduce and the version that you use.

**Comment by JaspalAujla** [comment]
I am using below Maven dependencies:

<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports</artifactId>
	<version>3.0.3</version>
</dependency>

<dependency>
	<groupId>com.vimalselvam</groupId>
	<artifactId>cucumber-extentsreport</artifactId>
	<version>2.0.4</version>
</dependency>

Below I have written GIVEN WHEN and THEN sections and code under these. Here, no matter my test case get failed when I try to open url or I want to click on element or I want to verify element displayed. The screenshot is always displaying under Then section:

    @Given("^I am on application home pager$")
    public void i_am_on_application_home_page() throws Throwable {
        driver.get(url));
    }

    @When("^I click on link$")
    public void i_click_on_link throws Throwable {
        driver.findElement(By.id(link)).click();
    }

    @Then("^I should see new page 2$")
    public void i_should_see_new_page() throws Throwable {
          driver.findElement(By.id(elementId)).isDisplayed();
    }

Below is the code to capture screenshot:

@After()
    public void tearDown(Scenario scenario) {
    	if (scenario.isFailed()) {
			try {
				String screenshotPath = screenshotManager.getScreenshot("output");  \\ Here, screenshotManager is another class to handle (capture) screenshot and return path of screenshot.

		     Reporter.addScreenCaptureFromPath(System.getProperty("user.dir")+"\\"+screenshotPath);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
    }

Note:- I am capturing screenshot in After class, not in GIVEN, WHEN or THEN

**Comment by email2vimalraj** [comment]
That is because Cucumber parses all the other steps even when your 1st step is failed and marking all the other remaining steps are skipped. So the `@After` hook executes only when after the last step is parsed. Hence, the screenshot is always attaching to the last step, irrespective of THEN keyword.

I'll try and see whether I can provide any solution to this.

**Comment by email2vimalraj** [comment]
@JaspalAujla This can't be fixed as I have the limitation from the Cucumber itself. Feel free to raise a PR if you find any work around.
