### ISSUE TITLE
Extra Scenario name at the top of steps creates confusion

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#39]
Scenario name at the top of steps should not be available. Instead of this there should be Examples table displayed permanently if available which would never hide.
![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24533111/ef783984-1621-11e7-8344-7664aa8f4ec5.PNG)

It looks more bad when we don't have Examples (multiple scenarios):
![cucumberextent2](https://cloud.githubusercontent.com/assets/17103120/24533149/3c224c2a-1622-11e7-9291-d11f57de9a6f.PNG)

**Comment by email2vimalraj** [comment]
This should be fixed as part of #38

**Comment by email2vimalraj** [comment]
Update to the latest version 3.0.0
