### ISSUE TITLE
CucumberExtentReport- Can you provide the option to add the HeadLine of the test report

### ISSUE THREAD

**Issue by perwez123** [email2vimalraj/CucumberExtentReporter#4]
Is there any way to add the Report headline in CucumberExtentReport right now , If not then please provide the option to add this in the report . Its very much important to add the name of it .

This is an enhancement request .

**Comment by email2vimalraj** [comment]
This will be added as part of the next release.

**Comment by email2vimalraj** [comment]
Completed as part of the new release v1.1.0. Kindly update your pom and refer the readme to know more about this.
