### ISSUE TITLE
Cucumber keywords should be bold

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#40]
Cucumber keywords should be bold:

![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24533506/be393b90-1624-11e7-975f-8dcbe2a038dc.PNG)

**Comment by anshooarora** [comment]
You should use the BDD style report:  http://extentreports.com/docs/versions/3/java/#create-bdd-tests

Example:  http://extentreports.com/samples/extent-bdd.html

**Comment by email2vimalraj** [comment]
This should be fixed as part of #38

**Comment by email2vimalraj** [comment]
Update to the latest version 3.0.0
