### ISSUE TITLE
"Scenario" and "Scenario Outline" not well managed

### ISSUE THREAD

**Issue by JaspalAujla** [email2vimalraj/CucumberExtentReporter#41]
If the Scenario does not have Example table then it should be Scenario only, not Scenario Outline
![cucumberextent](https://cloud.githubusercontent.com/assets/17103120/24533673/b79b34b8-1625-11e7-9519-231f69b18881.PNG)

If the Scenario has Examples then it should be Scenario Outline only, not Scenario
![cucumberextent2](https://cloud.githubusercontent.com/assets/17103120/24533691/cc2172b2-1625-11e7-9f5f-8edad3a7c057.PNG)

**Comment by email2vimalraj** [comment]
@JaspalAujla : How your feature file look like?

Don't you have the Scenario Outline when there is no Example. Kindly post the feature file that you are referring.

**Comment by JaspalAujla** [comment]
Below is a screenshot of Feature file:

![cucumberextentissuehelp](https://cloud.githubusercontent.com/assets/17103120/24581667/da335484-1773-11e7-8066-c0da375a7a03.png)

**Comment by email2vimalraj** [comment]
@JaspalAujla : Since ExtentReport has a BDD without Scenario Outline support, I'm planning to use that approach. Need your input here. Do you think really we need to log the Scenario Outline, or just logging all the Scenarios is fair enough to show in the report?

**Comment by JaspalAujla** [comment]
It would be same, we want to skip 1 less severity feature from the product. If you will leave this feature that will not create any problem, but to make more accurate BBD Gherkin style report you have to include this.

It is all about quality. As per the risk analysis, the result would be very minor if you would not add it.

**Comment by email2vimalraj** [comment]
Now updated to the latest version of extent report. Presentation of scenario outline and scenario is managed by extent report. Kindly update to the latest version 3.0.0.
