### ISSUE TITLE
Unable to get Feature and Scenarios pie chart in the dashbord

### ISSUE THREAD

**Issue by karthikeselene** [email2vimalraj/CucumberExtentReporter#47]
Hi Vimalraj,

I'm unable to get Feature and Scenarios pie chart in the dashbord. Shall I made any mistakke???

below one was sample report from extentreport BDD

![image](https://cloud.githubusercontent.com/assets/20849273/25431075/b2fcea74-2a9c-11e7-8aff-4feaa7d4a616.png)

**Comment by email2vimalraj** [comment]
@karthikeselene : this seems to be you are using a plain extent report. I recommend you to raise this issue [here](https://github.com/anshooarora/extentreports-java) for easy to track and get more visibility.
