### ISSUE TITLE
CucumberExtentReport- How to add the environment name in the test report

### ISSUE THREAD

**Issue by perwez123** [email2vimalraj/CucumberExtentReporter#5]
Can you provide the option to add the environment name into the report . I think the best way is , let this job to be done by the plugins itself rather than user pass the parameters.

I would like to add the following environment name in the report .

Browser name 
Browser Version
Selenium Version
Cucumber Version

**Comment by email2vimalraj** [comment]
It will be available as part of the next release.

**Comment by email2vimalraj** [comment]
Use the new release v1.1.0 to add the system information. Kindly refer the readme.
