### ISSUE TITLE
Custom report file

### ISSUE THREAD

**Issue by tronghieu** [email2vimalraj/CucumberExtentReporter#50]
Hi author,
I'm using your great plugin. I want custom report file name. I truy set filePath (the code below), but it did not work.
```
Reporter.getExtentHtmlReport().config().setFilePath("src/test/resources/"
                +System.getProperty("user.name") +reportFileName);
```
How could I do that?

**Comment by email2vimalraj** [comment]
@tronghieu : From v3.0.0, you can set the custom report file name. Update your dependency and give a try.

**Comment by tronghieu** [comment]
Thank so muck!

**Comment by sasikala-codoid** [comment]
I have tried this,
Reporter.getExtentHtmlReport().config().setFilePath("src/test/resources/"
                +System.getProperty("user.name") +reportFileName);

but it is not working.
