### ISSUE TITLE
report load failed

### ISSUE THREAD

**Issue by junejan143** [email2vimalraj/CucumberExtentReporter#53]
![qq 20170707105308](https://user-images.githubusercontent.com/15794075/27941293-9098bce4-6302-11e7-9f89-121c2edf0e52.png)
hi ,the css file can't load online ,do you have a way to workaround, thanks

**Comment by email2vimalraj** [comment]
It may be because you don't have an internet access, the CSS are loaded from extent's CDN. So kindly check your Developer tools to find whether the resources are loaded.
