### ISSUE TITLE
Enhancement request :  Screenshot 

### ISSUE THREAD

**Issue by jagadishchandran** [email2vimalraj/CucumberExtentReporter#54]
Hi Vimal,

For attaching screenshot to the report, you have a function[addScreenCaptureFromPath(String imagePath)] to pass the screenshot path.  So when the report is generated the images are perfectly loading in report.html. But if I want to share the report by placing the report.html and image folder in the shared location,  the images are not loading in the report because, the image path is absolute and the image location is changed now.  If you can make change to make screenshot folder as a child folder of the report folder as default. Then we can very well share the report with image loading as expected.

Thanks,
Jagadish

**Comment by email2vimalraj** [comment]
Kindly raise this issue [here](https://github.com/anshooarora/extentreports-java)
