### ISSUE TITLE
Scenario count within Scenario Outline

### ISSUE THREAD

**Issue by Fraser1994** [email2vimalraj/CucumberExtentReporter#56]
I've noticed that the dashboard count for the number of scenarios is not accurate when using Scenario Outlines. For example, I run one scenario outline which contains 4 separate tests(scenarios). One of these fails, the others pass but the dashboard will show all as failing.

Hoping this can be fixed to give a more accurate picture of the success rate for a large test suite

**Comment by email2vimalraj** [comment]
Scenario outline is the parent of all scenarios. So if a single scenario in the outline fails, by default your scenario outline will be marked as Failure. It would be great if you can provide a sample code along with the screenshot to understand it better.
