### ISSUE TITLE
How to deal with screenshots created only when the scenario failed and the Reporter.addScreenCaptureFromPath("path of the screenshot") method

### ISSUE THREAD

**Issue by dmtraining** [email2vimalraj/CucumberExtentReporter#62]
Hi,

In my Hook class, I take a screenshot "failed-step.png" only when the scenario is failed. 
After that, I call Reporter.addScreenCaptureFromPath("failed-step.png"); to insert this screenshot in the report.
It works fine when I have only 1 failed scenario but not when I have several. Each time a scenario failed, the same file "failed-step.png" is used. 
The result of this behavior is that at the end, "failed-step.png" will match with the last scenario failed and this same screenshot will be linked to all failed scenarios.
How do you deal with such kind of case?

**Comment by dmtraining** [comment]
Any idea?

**Comment by dmtraining** [comment]
Any input?

**Comment by buekera** [comment]
Try using dynamic file names otherwise you will overwrite the file each time.
Here is my code to take screenshots:

```
if (scenario.failed) {
    File screenshot = ((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.FILE)
    File screenFile = new File('reports/' + screenshot.name)
    Files.copy(screenshot, screenFile)
    Reporter.addScreenCaptureFromPath(screenFile.name)
}
```
This will create screenshots with random names, so you do not overwrite existing screenshots.

Hope this helps!

**Comment by email2vimalraj** [comment]
@dmtraining as highlighted by @buekera, the fundamental problem is in how you generate the file. Extent report attaches the file which you pass. Everytime you pass `failed-step.png`, that is the reason you see the same file. Try using dynamic one and your problem will be solved.
