### ISSUE TITLE
Not able to append to existing report

### ISSUE THREAD

**Issue by buekera** [email2vimalraj/CucumberExtentReporter#63]
I would love to get the functionality back which allowed me to append my report to an existing one. 

My current setup looks something like this:

```
@RunWith(Cucumber)
@CucumberOptions(
        features = ['src/test/resources/features/feature.feature'],
        glue = ['classpath:my.classpath.steps'],
        plugin = ['pretty', 'com.cucumber.listener.ExtentCucumberFormatter:reports/report.html'],
        tags = ['@Working']
)
class ProductRunner {

    @AfterClass
    static void teardown() {
        Reporter.loadXMLConfig(new File('src/test/resources/extent-config.xml'))
        Reporter.getExtentHtmlReport().setAppendExisting(true)
    }
}
```

When using the code above the existing report will always be overwritten by the new one.

I tried different versions (2.0.4, 3.0.0, 3.0.1) but none of these are working. The last version it worked was 1.1.1 I think.

Kind regards

**Comment by buekera** [comment]
Did anyone look into this yet?

Kind regards

**Comment by email2vimalraj** [comment]
@buekera : Append to existing report is not supported natively by extent report community version now. So can't help much on this.
