### ISSUE TITLE
addScenarioLog does nothing

### ISSUE THREAD

**Issue by lewisob** [email2vimalraj/CucumberExtentReporter#64]
Hi can someone please tell me what is the expected behaviour of `Reporter.addScenarioLog()` ?

I have attempted to use it but the text doesn't appear on the report. `addStepLog()` is however working as expected.

Any ideas?

Thanks.

**Comment by email2vimalraj** [comment]
`addScenarioLog` adds the log message under the scenario name as follows:

<img width="728" alt="screen shot 2018-01-04 at 8 24 21 am" src="https://user-images.githubusercontent.com/1214686/34548555-c269ba98-f128-11e7-94bd-bac498c3b248.png">

Feel free to re-open in case of further help required.

**Comment by rahulkamboj14** [comment]
are you still looking into this issue?

**Comment by lewisob** [comment]
Yes.

Still no fix?
