### ISSUE TITLE
klov support

### ISSUE THREAD

**Issue by buekera** [email2vimalraj/CucumberExtentReporter#67]
I was just wondering if there is already support for klov (will displace ExtentX server in the near future).

Let me know if anybody knows something about this.

Kind regards

**Comment by anshooarora** [comment]
There are 2 ways to do this:

1. Add a KlovReporter getter here:  https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/src/main/java/com/cucumber/listener/Reporter.java
2. Or simply, create an instance of this reporter and attach to ExtentReports:

```
KlovReporter klov = new KlovReporter();
klov.setProjectName("Extent");  // project name
klov.setReportName("BuildName");  // build name
klov.setKlovUrl("http://localhost");  // url where Klov is running
klov.initMongoDbConnection("localhost", 27017);  // mongo-db address

Reporter.getExtentReport().attachReporter(klov);
```

**Comment by buekera** [comment]
Oh wow, sounds pretty easy :-)
Thanks for the fast response!

**Comment by email2vimalraj** [comment]
I'll be adding native support for klov in the upcoming release.

**Comment by buekera** [comment]
@email2vimalraj sounds great! :)

**Comment by veeramanikandanvv** [comment]
@anshooarora: is there any way to select  project->subproject like style in extentx report. Say for example I need to select project in the tree structure as release name-test environment- product- ... Can you please help me on the same

**Comment by csiegler** [comment]
@email2vimalraj Hello! This is a wonderful plugin that my team is using for reports and integrating with Klov server. Is there any timeline on when the release including native klov support will be published? Thanks~

**Comment by msingh3** [comment]
@email2vimalraj: i added klov support for one of the projects I was working on. If you want I can commit that to the default branch to save you some.

**Comment by buekera** [comment]
@msingh3 That would be awesome!

**Comment by msingh3** [comment]
@buekera : I dont have access to push commits to this repo.

**Comment by buekera** [comment]
@msingh3 Just create a pull request, no reason to wait at all. I highly doubt that he will give you write acces to his repo :P

**Comment by email2vimalraj** [comment]
@msingh3: That would be great. I appreciate a PR since I'm busy with other
things.
@buekera: Thanks for assisting people actively.



Thanks
Vimalraj
http://vimalselvam.com
https://www.gitshowcase.com/email2vimalraj

**Comment by buekera** [comment]
@email2vimalraj you're welcome!

**Comment by email2vimalraj** [comment]
Added the klov native support .

**Comment by RaghuveerA** [comment]
I need some help here 

what if my klov is not running (i just dont want to attach any screenshot). can i comment below line in my code.
klov.setKlovUrl("http://localhost");  // url where Klov is running

And what if my MongoDB is hosted on elsewhere and it has different and it has basic authentication.
klov.initMongoDbConnection("localhost", 27017);  // mongo-db address
