### ISSUE TITLE
I am not using maven. Installed jar but even then not running 

### ISSUE THREAD

**Issue by ssundar0** [email2vimalraj/CucumberExtentReporter#69]
cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ExtentHtmlReporter

**Comment by buekera** [comment]
Can we have some info on your maven configuration?

**Comment by ssundar0** [comment]
If I'm not using maven then is there need of that ?

**Comment by ssundar0** [comment]
As I am not using maven so do I need to get that information..

**Comment by buekera** [comment]
What are you using instead?

I just need a look at the config you are using to tell your application where to find the Extent Reporter. Also a code example would be nice. Maybe the error is there.

**Comment by email2vimalraj** [comment]
@ssundar0 : Add the extent report jar also as mentioned in the doc: https://github.com/email2vimalraj/CucumberExtentReporter#usage
