### ISSUE TITLE
Plugin closes extent on calling scenario.write()

### ISSUE THREAD

**Issue by SluisM1** [email2vimalraj/CucumberExtentReporter#7]
When calling cucumber Scenario.write() to inject additional information into the scenario log then the ExtentReporter plugin automatically closes the extent. As can be seen in the following snippet taken from the code:
```java
public void write(String s) {
        extent.close();
}
```

**Comment by SluisM1** [comment]
I will fork the project and try to improve/correct this. Will send a merge request when done.

**Comment by email2vimalraj** [comment]
Great fix. I'll review and merge your PR.

**Comment by email2vimalraj** [comment]
Merged the PR.
