### ISSUE TITLE
How to add reporting steps to utility classes other than step definition ones

### ISSUE THREAD

**Issue by ankitagupta0909** [email2vimalraj/CucumberExtentReporter#79]
Reporter.addStepLog can be used inside any of the step definition classes and the step will be reported in the html report. 
However, if same step is used in any other utility class (common methods) then those steps are not captured. 

Is there a functionality to do this?

**Comment by email2vimalraj** [comment]
@ankitagupta0909 : You can use `Reporter.setTestRunnerOutput("Sample test runner output message");` to log a message from anywhere. Please note that this log will not be attached to your scenario or step and will be logged under the TestRunner output tab in the report.
