### ISSUE TITLE
screenshot is not showing in Html report

### ISSUE THREAD

**Issue by 15d6d** [email2vimalraj/CucumberExtentReporter#80]
Hi vimal i am using  updated dependency of extent-reports ,I am not getting screenshot in my extent html report ,below the code :if (scenario.isFailed()) {
			try {
				scenario.write("Current Page URL is " + driver.getCurrentUrl());
				byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
				String randomString = getRandomString(5);
				File file = new File(
						"target/screenshot_failure/screenshot_" + scenario.getName() + "_" + randomString + ".png");
				file.getParentFile().mkdirs();
				FileOutputStream out = new FileOutputStream(file);
				out.write(screenshot);
				scenario.embed(screenshot, "image/png");
				out.close();
				extentTest.addScreenCaptureFromPath(path + "/target/screenshot-failure/screenshot_" + scenario.getName()+ "_" + randomString + ".png");
				extentTest.log(Status.FAIL, path + "/target/screenshot_failure/screenshot_" + scenario.getName()+ "_" + randomString + ".png");
						
			} catch (Exception somePlatformsDontSupportScreenshots) {
				System.err.println(somePlatformsDontSupportScreenshots.getMessage());
			}[report url ](https://drive.google.com/file/d/1Mv8vyYg0jJWygDSvBa-Hb1nviPJYM0CO/view?usp=sharing)

**Comment by 15d6d** [comment]
I resolved my problem.

**Comment by ashokkumarg** [comment]
How did you resolved can you tell the solution
