### ISSUE TITLE
Scenario Steps are not displayed with logs and Screenshots in when Scenario Outline is Used

### ISSUE THREAD

**Issue by akhiljosephk** [email2vimalraj/CucumberExtentReporter#84]
The local report which gets generated has all scenario steps with logs and screenshots
![2018-02-09_11h18_16](https://user-images.githubusercontent.com/29649102/36013618-3f851cf6-0d8b-11e8-9904-0981b9a2626f.png)
.But the same report when viewed in ExtentX has only Scenario Outline Example section details alone(Refer Screenshot).

Below given is the code snippet:

@BeforeClass
    public static void create_ExtentReport_properties() {
        try {
            ExtentProperties extentProperties = ExtentProperties.INSTANCE;
            extentProperties.setExtentXServerUrl(EXTENT_URL);
            extentProperties.setProjectName("Test");
            extentProperties.setReportPath("output/extent.html");
        }catch (Throwable e){
            logger.info("Exception in Before Class, proceeding with test execution  "+e.getMessage());
        }
    }

@AfterClass
    public static void teardown() {
      try {
          Reporter.loadXMLConfig(new File("src/test/resources/extent-config.xml"));
          Reporter.setSystemInfo("user", System.getProperty("user.name"));
          Reporter.setSystemInfo("os", "Windows");
          Reporter.setTestRunnerOutput("Test Execution result for Test Project");
          Reporter.assignAuthor(AUTHOR);
      }catch (Exception e){
         logger.info("Exception in After Class
![2018-02-09_11h09_08](https://user-images.githubusercontent.com/29649102/36013546-d013c02a-0d8a-11e8-8325-253f58a3dd46.png)
 "+e.getMessage());
      }
  }

**Comment by akhiljosephk** [comment]
When Scenario Outline is used, steps and screenshots are not displayed in ExtentX,whereas when Scenario is used steps are displayed but still Screenshots are missing.

**Comment by anshooarora** [comment]
ExtentX is no longer supported. Please use Klov.

**Comment by akhiljosephk** [comment]
Even after upgrading to Klov the result is the same. Issue is occurring when Scenario Outline is [used.](https://github.com/anshooarora/klov/issues/26)

![2018-02-28_14h37_35](https://user-images.githubusercontent.com/29649102/36779214-42b6c456-1c95-11e8-8648-f7455cb9655c.png)

**Comment by akhiljosephk** [comment]
This issue is similar to this [closed issue](https://github.com/email2vimalraj/CucumberExtentReporter/issues/45)

**Comment by akhiljosephk** [comment]
@anshooarora: Can you please help here

**Comment by anshooarora** [comment]
I am able to reproduce this.  Its an issue with Klov's templating.  Will release the fix with version 0.1.0.

**Comment by anshooarora** [comment]
Klov issue:  https://github.com/anshooarora/klov/issues/34

**Comment by anshooarora** [comment]
Fixed with version 0.1.0.

**Comment by baraths84** [comment]
@akhiljosephk  can you help with a sample project using Klov with Junit,Cucumber. 
1)I am following the steps you mentioned here https://github.com/anshooarora/klov/issues/26 . I am new to Klov/extentreports and unable to pipe data to Klov.. 
2)ExtentCucumberFormatter formatter =new ExtentCucumberFormatter(file);
how is the formatter used before attaching to the reporter.

Thanks in advance!

**Comment by email2vimalraj** [comment]
@baraths84 : We have the klov support added natively in the Cucumber Extent reporter. Kindly update the version to 3.1.0 and start using it. Thanks.
