### ISSUE TITLE
CucumberExtentReporter is not generated during runtime and Gherkin Keywords are repeated in report

### ISSUE THREAD

**Issue by benz-philip** [email2vimalraj/CucumberExtentReporter#85]
Below is the configuration in cucumber runner,

@CucumberOptions(features = "xxxx", glue = "cucumber.stepDefinitions", plugin = {
		"com.cucumber.listener.ExtentCucumberFormatter:",
		"rerun:output/rerun.txt" }, format = { "pretty", "html:target/Destination" } ,tags = { "@TestAuto" })

@BeforeClass
public static void setup() {
    ExtentProperties extentProperties = ExtentProperties.INSTANCE;
    extentProperties.setReportPath("output/myreport.html");
}

@AfterClass
    public static void teardown() {
        Reporter.loadXMLConfig(new File("src/test/resources/extent-config.xml"));
}

===========================================================

In previous releases, the extent report was generated once one feature is completed and was updated by completion of each feature

But in the latest version, the report gets generated only after the automation run is completed. we need to wait till the execution is completed to check the result. It impact if there are many number of features.

For me, the automation test execution is more than 2 days. I used to check the results in between. but it is not possible now.

And also, In reports, the gherkin keywords are repeated.. refer below,
![screen shot 2018-02-12 at 5 47 39 pm](https://user-images.githubusercontent.com/18724283/36100105-8c1ecc3e-101e-11e8-9806-f7455d9469b3.png)

If this is not issue, please suggest me the right implementation. Dont know if this is the right platform

**Comment by email2vimalraj** [comment]
@benz-philip : We never implemented to generate report files for every feature. May be it was working wrongly earlier, could have been fixed.

However, to help you out, you could have different runner class for each feature to overcome this problem.
