### ISSUE TITLE
Authors and Categories view missing info when appending to existing report

### ISSUE THREAD

**Issue by johnmorand** [email2vimalraj/CucumberExtentReporter#88]
This is the scenario.
Test run which has author "Author_A"  assigned and groups of "testA" and "smoke" set
Report created and author and groups shown correctly in Categories and also in "Authors" view

Another test run which has author "AuthorB" and groups of "testB" and "performance", with the AppendExisting flag set to true. 

Authors view only shows AuthorB and Categories view only shows testB and performance. 
Tests view shows all tests and all authors and categories correctly though.

**Comment by email2vimalraj** [comment]
@johnmorand : CucumberExtentReporter doesn't directly deal with ExtentReport APIs. This issue is more like ExtentReport. Kindly report over there.
