### ISSUE TITLE
Add ability to append browser being used for each feature under the list of features

### ISSUE THREAD

**Issue by jas7002** [email2vimalraj/CucumberExtentReporter#94]
When running feature files and using a testng xml file to run them on three different browsers, each feature will appear three different times on the left hand side of the extent report. There should be a way to append the name of the browser being used for each feature, much like how you can append the date and time for them. Below is an example of a report where I run the feature "Login Page Invalid Logins" on three different browsers, and you cannot distinguish the difference between them just by looking at the name of the feature:
![image](https://user-images.githubusercontent.com/21295593/40990708-b650db1a-68bf-11e8-8d29-30ad613220ad.png)

**Comment by Fraser1994** [comment]
I'm currently doing this via reflection - editing the feature name before it is handed to the reporter to add the run config used. That would be one way of doing this if your need is urgent

**Comment by email2vimalraj** [comment]
@jas7002 : This request is more of like the ExtentReport core. Kindly raise there. Reopen in case I can help on this repo.
