### ISSUE TITLE
Unable to implement for my project

### ISSUE THREAD

**Issue by Harishpublic** [email2vimalraj/CucumberExtentReporter#99]
pardon my ignorance. I followed all the steps detailed here.  can you please help me to get extent-config.xml file.  am getting error for this file when I run my tests.

**Comment by email2vimalraj** [comment]
Do you really need the `extent-config.xml` file? Are you doing any customizations on the report? If so, then only you need that file, otherwise comment it out. For more information about the config xml file, kindly read this: http://extentreports.com/docs/versions/3/java/#config-xml-community
